### ISSUE TITLE
Using derived classes in listener prototype causes compile-time error

### ISSUE THREAD

**Issue by egorkrestinin** [wqking/eventpp#10]
*Steps to reproduce:*
compile this code
```
class Event {
    public: 
        int type;
};

class DerivedEvent : public Event {
    public: 
        int data;
};

struct EventPolicies
{
	static int getEvent(const Event& e) {
		return e.type;
	}
};

void app_main() {
    eventpp::EventDispatcher<int, void (const Event&), EventPolicies> dispatcher;
    dispatcher.appendListener(3, [](const DerivedEvent& e) {
	    std::cout
		    << std::boolalpha
		    << "Event::type is " << e.type << std::endl
	    ;
    });

    DerivedEvent event;
    event.type = 3;
    event.data = 5;
    dispatcher.dispatch(event);
}
```

*Expected behaviour:*
Code to be compiled

*Actual behaviour:*
Got an error 
```
src/main.cpp: In function 'void app_main()':
src/main.cpp:94:6: error: no matching function for call to 'eventpp::EventDispatcher<int, void(const Event&), EventPolicies>::appendListener(int, app_main()::<lambda(const DerivedEvent&)>)'
```

When I changed in the listener callback prototype ` [](const DerivedEvent& e)` to ` [](const Event& e)` it compiles perfectly. I could create instances of EventDispatcher for each event type, but not sure if  it's a good idea.
Is there a possibility to use derived classes in prototype?

**Comment by wqking** [comment]
> When I changed in the listener callback prototype [](const DerivedEvent& e) to [](const Event& e) it compiles perfectly. I could create instances of EventDispatcher for each event type, but not sure if it's a good idea.   

Not only it's a good idea, but also it's the correct and proper way. Go ahead with it.

> Is there a possibility to use derived classes in prototype?  
Technically `eventpp` can be modified to support that, but that's dangerous and we should not do it.  
Just use the base class in the listener prototype, then type cast it to the derived class, that's the common way how it works.

**Comment by egorkrestinin** [comment]
Works fine with type casting. Thank you.
