### ISSUE TITLE
CallbackList move assignement operator create memory leak

### ISSUE THREAD

**Issue by OlivierLDff** [wqking/eventpp#12]
The operator `CallbackListBase & operator = (CallbackListBase && other)` only release head and tail. 
* If there is one callback, then the node is destroyed. 
* If there is more, then they keep reference between each other and never get destroyed.

I fixed the problem on my fork in a branch [move-assignement-fix](https://github.com/OlivierLDff/eventpp/tree/move-assignment-fix)

Fix  in callbacklist.h
``` cpp
	CallbackListBase & operator = (CallbackListBase && other) noexcept {
		if(this != &other) {
			while(head) {
				// Create copy because doFreeNode reset temp->counter
				// after head reassignment.
				auto temp = head;
				doFreeNode(temp);
			}
			head = std::move(other.head);
			tail = std::move(other.tail);
			currentCounter = other.currentCounter.load();
		}
	}
```

And the unit test demonstrating the problem:
``` cpp
TEST_CASE("CallbackList, move assignement")
{
	using CL = eventpp::CallbackList<void()>;
	CL callbackList;
	const auto h1 = callbackList.append([]() {});
	const auto h2 = callbackList.append([]() {});
	callbackList = {};

	// Make sure nodes were destroyed
	REQUIRE(h1.expired());
	REQUIRE(h2.expired());
}
```

Would you consider a PR for this?

**Comment by wqking** [comment]
Good job. I will merge your PR and do some tests.

**Comment by OlivierLDff** [comment]
Thank you!

**Comment by wqking** [comment]
I refactored the code and improved the unit test.
Also, I don't understand what `auto temp = head` does and what your comment means in your original code (now they were gone)
```
// Create copy because doFreeNode reset temp->counter
// after head reassignment.
auto temp = head;
doFreeNode(temp);
```
I think `temp` is just a copy of the shared_ptr of `head`, so it doesn't prevent the counter from being modified.
If I misunderstand you, let me know.

**Comment by OlivierLDff** [comment]
`doFreeNode` take a reference to a shared_ptr.
If doing `doFreeNode(head)`, then when `head = node->next;` at line 346 is the equivalent of doing `node = node->next`.
This mean that line 357: `node->counter = removedCounter;` is working on the second node. Not the one we removed.

You can try to do `while(head) doFreeNode(head);` it will crash.

Another alternative would be to move `node->counter = removedCounter;` upper in `doFreeNode` function.

Hope this is clear.

**Comment by OlivierLDff** [comment]
Anyway your solution is more elegant. In mine i wanted to do minimal change to make code review fast.

**Comment by wqking** [comment]
I understand now, and I've fixed it though it never causes trouble :-)
