### ISSUE TITLE
Adding Ci with github actions

### ISSUE THREAD

**Issue by OlivierLDff** [wqking/eventpp#15]
I'm adding ci with GH actions with lots of my small project because it's so easy to do.
I tried to add it to eventpp on a branch on my repo. https://github.com/OlivierLDff/eventpp/actions
As you can see tests are not compiling on macOs.

Would you be interested in such a PR? I can also fix compilation error on mac when i will have time.
I think it can be cool to have at least CI for windows/ubuntu in Release

**Comment by wqking** [comment]
Yes, go ahead. It would be great to have CI integrated.  
I can't fix issues for MacOS because I don't have any Mac machines nor virtual environments.

**Comment by OlivierLDff** [comment]
I created a PR with windows and ubuntu which work. I will push later for mac with fix
