### ISSUE TITLE
Not compatible with C++11 compiler version?

### ISSUE THREAD

**Issue by shellinspector** [wqking/eventpp#19]
Dear eventpp developers,
I really love this library, and have used it before in a PC project. Lately I started to work on embedded ARM Linux project where the gcc cross-compiler is set to C++11 standard. No way to upgrade to C++17. To my disappointment, when using eventpp, I am facing compilation problems. I believe they are due to use of _**fold expressions**_ that only appear in  C++17. They do resemble _**parameter packs**_ (C++11) but not quite the same. Could you please confirm that the problem I am seeing is due to my compiler not supporting C++17? If yes, could you please provide some advice on how I can rewrite the expressions to fit the C++11 standard. 
My compiler: arm-none-linux-gnueabi-g++ (Sourcery CodeBench Lite 2014.05-29) 4.8.3 20140320 (prerelease)

My compile errors:

> host/bin/arm-none-linux-gnueabi-g++ -g -DDEBUG=1 -O0 -std=c++11 -D__cplusplus=201103L -fmessage-length=0 -DISO_DATE=`date -u +'"%Y-%m-%dT%H:%M:%S"'` -DGIT_BRANCH=\"`git name-rev --name-only HEAD`\" -DGIT_REV=\"`git log -1 --pretty=%h`\" -I../CommandHandlers/src -I../DataLinkCommunicators/src -I../ElvisDataModel/sr
> c -I../DriverCommunicators/src -I../ScpiServerCmdsCommunicator/src -I../ClientBaseServerCmdsCommunicators/src -I../../Common/src -I../BAL/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder
> /_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/CommandHandlers/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achille
> s2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/DataLinkCommunicators/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/
> ControlLink/ScpiServer/ElvisDataModel/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/DriverCommunicators/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/ScpiServerCmdsCommunicator/src -I/home/maxim
> /workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/ClientBaseServerCmdsCommunicators/src -I/home/maxim/workspace/elvis/
> 3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/../Common/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder
> /_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/BAL/src -I../../IdqCppSdk/logger/src -I../../IdqCppSdk/Util/src -I../../../IdqCppSdk/logger/src -I../../../IdqCppSdk/Util/src 
> -I../../../IdqCppSdk/eventpp/include -c src/EvtQueue.cpp -o Debug/EvtQueue.o                                                                                                                                         
> In file included from ../../../IdqCppSdk/eventpp/include/eventpp/eventdispatcher.h:17:0,
>                  from ../../../IdqCppSdk/eventpp/include/eventpp/eventqueue.h:17,
>                  from src/EvtQueue.h:20,
>                  from src/EvtQueue.cpp:1:
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h: In member function 'void eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const':
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:260:19: error: expected ',' before '...' token
>    forEachIf([&args...](Callback & callback) -> bool {
>                    ^
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:260:19: error: expected identifier before '...' token
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:260:22: error: parameter packs not expanded with '...':
>    forEachIf([&args...](Callback & callback) -> bool {
>                       ^
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:260:22: note:         'args'
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h: In lambda function:
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:261:17: error: expansion pattern 'args' contains no argument packs
>     callback(args...);
>                  ^
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:262:56: error: expansion pattern 'args' contains no argument packs
>     return CanContinueInvoking::canContinueInvoking(args...);
>                                                         ^
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h: In instantiation of 'struct eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const [with PoliciesType = even
> tpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]::__lambda2':
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:263:4:   required from 'void eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const [with PoliciesType = even
> tpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]'
> ../../../IdqCppSdk/eventpp/include/eventpp/eventdispatcher.h:228:47:   required from 'void eventpp::internal_::EventDispatcherBase<EventType_, ReturnType(Args ...), Policies_, MixinRoot_>::directDispatch(const Eve
> nt&, Args ...) const [with EventType_ = bal::EventType; Policies_ = eventpp::DefaultPolicies; MixinRoot_ = eventpp::internal_::EventQueueBase<bal::EventType, void(bal::EventType, const std::basic_string<char>&, st
> d::shared_ptr<bal::GeneralArgs>), eventpp::DefaultPolicies>; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralAr
> gs>}; eventpp::internal_::EventDispatcherBase<EventType_, ReturnType(Args ...), Policies_, MixinRoot_>::Event = bal::EventType]'
> ../../../IdqCppSdk/eventpp/include/eventpp/eventqueue.h:411:3:   required from 'void eventpp::internal_::EventQueueBase<EventType_, ReturnType(Args ...), Policies_>::doDispatchQueuedEvent(T&&, eventpp::internal_::
> IndexSequence<Indexes ...>) [with T = eventpp::internal_::EventQueueBase<bal::EventType, void(bal::EventType, const std::basic_string<char>&, std::shared_ptr<bal::GeneralArgs>), eventpp::DefaultPolicies>::QueuedEv
> ent_&; unsigned int ...Indexes = {0u, 1u, 2u}; EventType_ = bal::EventType; Policies_ = eventpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, st
> d::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]'
> ../../../IdqCppSdk/eventpp/include/eventpp/eventqueue.h:259:5:   required from 'bool eventpp::internal_::EventQueueBase<EventType_, ReturnType(Args ...), Policies_>::processOne() [with EventType_ = bal::EventType;
>  Policies_ = eventpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]'
> src/EvtQueue.cpp:54:27:   required from here
> ../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:260:15: error: using invalid field 'eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const::__lambda2::__args
> '
>    forEachIf([&args...](Callback & callback) -> bool {
>                ^
> make[3]: *** [/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/../mk/common.mk:104: Debug/EvtQueue.o] Erro
> r 1
> make[2]: *** [Makefile:9: all] Error 2

**Comment by wqking** [comment]
Hi shellinspector, thanks for the bug report. eventpp is designed to only require C++11. If it requires higher C++ version, there maybe something wrong.
I will look into the issue and get back to you later.

**Comment by wqking** [comment]
I did some tests and research.
The library doesn't require any C++17 feature, nor fold expressions.
I set GCC standard to C++11 and it compiles fine. (note the unittest requires C++14 but the library doesn't).  

The code that caused your issue conforms to C++11, search either 'capture' or 'pack' in below cppreference pages,
https://en.cppreference.com/w/cpp/language/lambda  
https://en.cppreference.com/w/cpp/language/parameter_pack  

I believe the issue is caused by that GCC v4.8.3 doesn't support all C++11 features.

You can do a test, in callback.h, in about line 260 in the function `operator ()`, change  

```
forEachIf([&args...](Callback & callback) -> bool
```
  
to
```
forEachIf([&](Callback & callback) -> bool
```
 
Remove `args...`  
According to this post,  
https://stackoverflow.com/questions/18871122/compiler-bug-or-non-standard-code-variadic-template-capture-in-lambda  
You should get a more meaningful error message,  

>> sorry, unimplemented: use of ‘type_pack_expansion’ in template  

If you get similar error, most likely you either need to upgrade GCC if possible, or can't use `eventpp` for now.  

I hope I can find a Windows or Linux version of GCC v4.8.3 to do more tests.

**Comment by wqking** [comment]
>> or can't use eventpp for now.  

This may be not true. Another solution is that you try to expand the operator() with the function body code in `forEachIf`, and thus `doForEachIf`. That should be not difficult. Before doing that, you can try to remove the code that caused error in operator() to see if there are any other errors, if not, it may worth to expand the operator().
If you do so, let me know the result, and I may improve the library code.

**Comment by shellinspector** [comment]
Thanks, **wqking,** for such a quick respose! I will experiment with your last suggestion. For now, I removed the ... from the lambdas [] brackets replacing with [&], as you suggested and now get a different but similar error. Still something wrong with parameter packs. You are right, just using my g++ on Ubuntu with **-std=c++11 __cplusplus=201103L** flags compiles just fine. 

Here is how it now fails to compile with the ARM gcc cross-compiler:
> host/bin/arm-none-linux-gnueabi-ar -r Debug/libCommon.a Debug/HistogramType.o Debug/CouplingType.o Deb
ug/CoincidenceRefType.o Debug/Common.Decl.o Debug/ResolutionType.o Debug/SyncType.o Debug/SignalType.o Debug/DigiSignalMode.o Debug/StatisticType.o Debug/Common.Util.o Debug/SignatureVerifier.o Debug/ControlLinkEx
ception.o Debug/ResyncType.o Debug/Inf.o Debug/GeneratorType.o Debug/EdgeType.o Debug/License.o Debug/CounterModeType.o Debug/TriggerType.o Debug/TSCombinerType.o Debug/PllStateType.o Debug/InputSelectType.o
/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/host/bin/arm-none-linux-gnueabi-ar: creating Debug/libCommon.a
/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/host/bin/arm-none-linux-gnueabi-g++ -g -DDEBUG=1 -O0 -std=c++11 -D__cplusplus=201103L -fmessage-length
=0 -DISO_DATE=`date -u +'"%Y-%m-%dT%H:%M:%S"'` -DGIT_BRANCH=\"`git name-rev --name-only HEAD`\" -DGIT_REV=\"`git log -1 --pretty=%h`\" -I../CommandHandlers/src -I../DataLinkCommunicators/src -I../ElvisDataModel/sr
c -I../DriverCommunicators/src -I../ScpiServerCmdsCommunicator/src -I../ClientBaseServerCmdsCommunicators/src -I../../Common/src -I../BAL/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder
/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/CommandHandlers/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achille
s2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/DataLinkCommunicators/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/
ControlLink/ScpiServer/ElvisDataModel/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/DriverCommuni
cators/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/ScpiServerCmdsCommunicator/src -I/home/maxim
/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/ClientBaseServerCmdsCommunicators/src -I/home/maxim/workspace/elvis/
3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/../Common/src -I/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder
/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/BAL/src -I../../IdqCppSdk/logger/src -I../../IdqCppSdk/Util/src -I../../../IdqCppSdk/logger/src -I../../../IdqCppSdk/Util/src 
-I../../../IdqCppSdk/eventpp/include -c src/EvtQueue.cpp -o Debug/EvtQueue.o
In file included from ../../../IdqCppSdk/eventpp/include/eventpp/eventdispatcher.h:17:0,
                 from ../../../IdqCppSdk/eventpp/include/eventpp/eventqueue.h:17,
                 from src/EvtQueue.h:20,
                 from src/EvtQueue.cpp:1:
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h: In lambda function:
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:261:13: error: parameter packs not expanded with '...':
    callback(args...);
             ^
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:261:13: note:         'args'
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:261:17: error: expansion pattern 'args' contains no argument packs
    callback(args...);
                 ^
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:262:56: error: expansion pattern 'args' contains no argument packs
    return CanContinueInvoking::canContinueInvoking(args...);
                                                        ^
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h: In instantiation of 'struct eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const [with PoliciesType = even
tpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]::__lambda2':
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:263:4:   required from 'void eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const [with PoliciesType = even
tpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]'
../../../IdqCppSdk/eventpp/include/eventpp/eventdispatcher.h:228:47:   required from 'void eventpp::internal_::EventDispatcherBase<EventType_, ReturnType(Args ...), Policies_, MixinRoot_>::directDispatch(const Eve
nt&, Args ...) const [with EventType_ = bal::EventType; Policies_ = eventpp::DefaultPolicies; MixinRoot_ = eventpp::internal_::EventQueueBase<bal::EventType, void(bal::EventType, const std::basic_string<char>&, st
d::shared_ptr<bal::GeneralArgs>), eventpp::DefaultPolicies>; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralAr
gs>}; eventpp::internal_::EventDispatcherBase<EventType_, ReturnType(Args ...), Policies_, MixinRoot_>::Event = bal::EventType]'
../../../IdqCppSdk/eventpp/include/eventpp/eventqueue.h:411:3:   required from 'void eventpp::internal_::EventQueueBase<EventType_, ReturnType(Args ...), Policies_>::doDispatchQueuedEvent(T&&, eventpp::internal_::
IndexSequence<Indexes ...>) [with T = eventpp::internal_::EventQueueBase<bal::EventType, void(bal::EventType, const std::basic_string<char>&, std::shared_ptr<bal::GeneralArgs>), eventpp::DefaultPolicies>::QueuedEv
ent_&; unsigned int ...Indexes = {0u, 1u, 2u}; EventType_ = bal::EventType; Policies_ = eventpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, st
d::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]'
../../../IdqCppSdk/eventpp/include/eventpp/eventqueue.h:259:5:   required from 'bool eventpp::internal_::EventQueueBase<EventType_, ReturnType(Args ...), Policies_>::processOne() [with EventType_ = bal::EventType;
 Policies_ = eventpp::DefaultPolicies; ReturnType = void; Args = {bal::EventType, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<bal::GeneralArgs>}]'
src/EvtQueue.cpp:54:27:   required from here
../../../IdqCppSdk/eventpp/include/eventpp/callbacklist.h:261:13: error: using invalid field 'eventpp::internal_::CallbackListBase<ReturnType(Args ...), PoliciesType>::operator()(Args ...) const::__lambda2::__args
'
    callback(args...);
             ^
make[3]: *** [/home/maxim/workspace/elvis/3.Implementation/Software/FirmwareBuilder/_build/buildroot-2019.02.3/achilles2-dev/build/scpi-server-0.1/ControlLink/ScpiServer/../mk/common.mk:104: Debug/EvtQueue.o] Erro
r 1
make[2]: *** [Makefile:9: all] Error 2

**Comment by wqking** [comment]
I mean, try to remove the function body of operator() in callback.h, so the operator will look like,
```
	void operator() (Args ...args) const
	{
	}
```
Of course the code won't run properly but let's test to see if it compiles.
If there is no any other errors, we can do workaround for the issue. If there is other errors, paste here.
I'm gonna sleep and will response you tomorrow.

BTW, the gcc bug 85305 you posted is about init-capture in C++20, not related to the issue here. But I'm pretty sure your issue is caused by either bug in gcc 4.8.3 or it doesn't support C++11 completely.

**Comment by shellinspector** [comment]
Yes, commenting out the contents of the operator() like this

```
void operator() (Args ...args) const
{
        /*
     forEachIf([&args...](Callback & callback) -> bool {
            callback(args...);
            return CanContinueInvoking::canContinueInvoking(args...);
     });
        */
}
```
produces a clean compilation.

**Comment by wqking** [comment]
```
void operator() (Args ...args) const
{
	NodePtr node;

	{
		std::lock_guard<Mutex> lockGuard(mutex);
		node = head;
	}

	const Counter counter = currentCounter.load(std::memory_order_acquire);

	while(node) {
		if(node->counter != removedCounter && counter >= node->counter) {
			node->callback(args...);
			if(! CanContinueInvoking::canContinueInvoking(args...)) {
				break;
			}
		}

		{
			std::lock_guard<Mutex> lockGuard(mutex);
			node = node->next;
		}
	}
}
```

This new `operator()` may solve the issue, can you test? If it works, I will see how to fix it in an elegant way.

**Comment by shellinspector** [comment]
Hello wqking, yes, my simple test with an eventpp/eventqueue.h of your new version of operator does work.  Thanks.

**Comment by wqking** [comment]
I applied the patch on master, e608ab3c14e81526f06362312c02fe6b5cc6ee02
Please test if it works.
