### ISSUE TITLE
Cannot append callback

### ISSUE THREAD

**Issue by DSCriErr** [wqking/eventpp#20]
Hello,
I'm sure it is a super simple question, but I cannot handle the syntax. Could you please point out how to pass the instance of member function into it so it just work?

```
class MySettings
{
public:
...
eventpp::CallbackList<void(void)> AnySettingsUpdated;
}

```
```
class cMain : public wxFrame
{
protected:
	void OnAnySeetingsUpdate();
```
}

`MySettings.AnySettingsUpdated.append(&cMain::OnAnySeetingsUpdate);`

Which leaves me error:

> 1>c:\dev_pcn\ocr\code\ocrviaopencvwgui\ocrviaopencvwgui\cmain.cpp(52): error C2664: 'eventpp::internal_::CallbackListBase<Prototype_,Policies_>::Handle_ eventpp::internal_::CallbackListBase<Prototype_,Policies_>::append(const std::function<ReturnType (void)> &)': cannot convert argument 1 from 'void (__cdecl cMain::* )(void)' to 'const std::function<ReturnType (void)> &'
> 1>        with
> 1>        [
> 1>            Prototype_=void (void),
> 1>            Policies_=eventpp::DefaultPolicies,
> 1>            ReturnType=void
> 1>        ]
> 1>        and
> 1>        [
> 1>            ReturnType=void
> 1>        ]
> 1>c:\dev_pcn\ocr\code\ocrviaopencvwgui\ocrviaopencvwgui\cmain.cpp(52): note: Reason: cannot convert from 'void (__cdecl cMain::* )(void)' to 'const std::function<ReturnType (void)>'
> 1>        with
> 1>        [
> 1>            ReturnType=void
> 1>        ]
> 1>c:\dev_pcn\ocr\code\ocrviaopencvwgui\ocrviaopencvwgui\cmain.cpp(52): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by wqking** [comment]
This is not syntax problem in `eventpp`, you need to learn how to use `std::function` properly.  
See here,  
https://stackoverflow.com/questions/7582546/using-generic-stdfunction-objects-with-member-functions-in-one-class#:~:text=A%20non%2Dstatic%20member%20function,(and%20the%20only)%20argument.  

Or the example code here,  
https://en.cppreference.com/w/cpp/utility/functional/function
