### ISSUE TITLE
unused parameter 'args'

### ISSUE THREAD

**Issue by bd1es** [wqking/eventpp#21]
Hello,

One question, is it appropriate to replace the first line with the second one as shown below?
                static auto forEach(const Self * /*self*/, A && ...args)
                //static auto forEach(const Self * /*self*/, A && ...)
It's line 271 of “eventpp/eventdispatcher.h”.

Seems that, this removes a warning “unused parameter 'args'“ emitted from clang if -Wunused-parameter is on.

Thank you.

**Comment by wqking** [comment]
Thanks for the issue report.
I just fixed it on master, please check.

**Comment by bd1es** [comment]
Cloned, thank you.
