### ISSUE TITLE
EventDispatcher - detect no listeners

### ISSUE THREAD

**Issue by frostius** [wqking/eventpp#24]
I'd like to be able to handle the scenario where there are no listeners for an event.  In my specific case, I want to provide a default handler if there is not one.   Is there already a mechanism to determine if `dispatch()` did nothing?  

Perhaps `dispatch()` could return the listener count?

**Comment by wqking** [comment]
Hi, that is a good use case. I will see how to implement it. Most likely a method `hasAnyListener` is a good choice.

**Comment by frostius** [comment]
That works - thanks for the quick response.

The only reason I suggested a return from `dispatch()` is that it would avoid having to do an event type lookup for `hasAnyListener` and then another for `dispatch()`

**Comment by wqking** [comment]
I added function `hasAnyListener` on master branch.
Your proposal of returning the listener count from `dispatch` is good for performance, but it's not good for API design (such as, `dispatch` do more duties than it has to, it's inconsistent to `CallbackList` and `EventQueue`).  
I expect the extra event type look up in `hasAnyListener` is neglect in most cases.

**Comment by frostius** [comment]
Thanks!  I was glad to find a well designed and documented event 
library.  Appreciate the quick response and great documentation.

I made a personal fork that returns false when dispatch doesn't find any 
listeners.  I'm using dispatch in a performance critical loop and while 
I do love a consistent API, performance trumps aesthetics in this 
instance.

------ Original Message ------

**Comment by wqking** [comment]
Please let me know if you find any performance issue.
