### ISSUE TITLE
eventpolicies SingleThreading的bug

### ISSUE THREAD

**Issue by gelijian** [wqking/eventpp#29]
1. include/eventpp/callbacklist.h 158行用到了Atomic<T>::exchange method
2. include/eventpp/eventpolicies.h SingleThreading中的Atomic template未定义此方法

**Comment by wqking** [comment]
Thanks for the bug report. I fixed it in commit 7fe8fa8e081c9b33b93c62ccb5101212254206ea

**Comment by gelijian** [comment]
Thanks for your fast response, awesome project.
