### ISSUE TITLE
Movable ScopedRemover

### ISSUE THREAD

**Issue by Martinii89** [wqking/eventpp#31]
Would it be possible\make sense to make ScopedRemover movable?

**Comment by wqking** [comment]
That's good idea. I will check.

**Comment by Martinii89** [comment]
My idea was to be able to put it as a member variable that would manage the lifetime of the event subscriptions.
With it being movable it would be easier to assign this member outside of the constructor.
The drawback would be that you could move and keep alive callbacks referencing a dead /moved object. And that could lead to nasty surprises.

**Comment by wqking** [comment]
Added move constructor and move assignment operator on master branch.

>> The drawback would be that you could move and keep alive callbacks referencing a dead /moved object. And that could lead to nasty surprises.

ScopedRemover should be used in the way that, the underlying listener objects should not have longer lifetime than ScopedRemover. If we follow that rule, no matter how it's moved, it's safe and should not any crash.
