### ISSUE TITLE
Unit tests dont build

### ISSUE THREAD

**Issue by devbharat** [wqking/eventpp#37]
ubuntu 20.04
gcc 8.5

I updated catch.hpp like https://github.com/CelestiaProject/Celestia/pull/1118 and then it worked.

**Comment by wqking** [comment]
Thanks for the problem report.
I've update CATCH2 to v2.13.9.
Let me know if it works.

**Comment by devbharat** [comment]
Thanks for the quick action. Ill test it and reply.
