### ISSUE TITLE
Crash in winxp

### ISSUE THREAD

**Issue by willrebuild** [wqking/eventpp#41]
![image](https://user-images.githubusercontent.com/3365086/172353336-f18229ef-5c69-42df-ab7b-d138b98d4a8e.png)
![image](https://user-images.githubusercontent.com/3365086/172353454-0883d935-25a7-4913-b741-03aef59ca419.png)
![image](https://user-images.githubusercontent.com/3365086/172353675-c1d124d7-c598-4de8-8e6b-408a4beb527f.png)
My system is winxp sp3
It looks like there's some problem with std:mutex in winxp?

**Comment by wqking** [comment]
I think it's [a problem of system error](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/scheduler-resource-allocation-error-class?view=msvc-170).  
It should have nothing to do with `eventpp`.  
you may investigate whether the MSVC or STL works correctly on WinXP.
