### ISSUE TITLE
 EventQueue是异步的吗？/Is EventQueue asynchronous?

### ISSUE THREAD

**Issue by hctym1995** [wqking/eventpp#43]
我在我的代码中使用了eventpp的EventQueue接收来自其他线程的一系列事件：
我的理解是当调用EventQueue的enqueue方法以后，其他线程就可以继续添加新的事件了
但是从现象来看，一旦某一个任务没有处理完成，线程似乎就会阻塞
请问是我的用法有问题吗？

I'm using eventpp's EventQueue in my code to receive a series of events from other threads:
My understanding is that after calling the enqueue method of EventQueue, other threads can continue to add new events
But from the phenomenon, once a certain task is not processed, the thread seems to be blocked
Is there a problem with my usage?

**Comment by wqking** [comment]
>> My understanding is that after calling the enqueue method of EventQueue, other threads can continue to add new events

That's correct. That's how it's supposed to do.

>> But from the phenomenon, once a certain task is not processed, the thread seems to be blocked
>> Is there a problem with my usage?

Show me your code.

**Comment by hctym1995** [comment]
我封装了一个动态库，动态库的初始化方法会初始化一个eventpp::EventQueue，同时提供一个对外接口LibAddTask()
初始化eventqueue的时候，appendListener绑定的lamda函数中有一些我自己的后处理：
I encapsulated a dynamic library. The initialization method of the dynamic library will initialize an eventpp::EventQueue and provide an external interface LibAddTask()
When initializing the eventqueue, there is some post-processing of my own in the lamda function bound to the appendListener:

```c++
m_eventqueue.appendListener(1, [=](void *task, int tasktype)){
  func();
  func2();
});
```

```c++
LibAddTask(void *task)  
{ 
  eventqueue.enque(tasktype, task, mytype);  
  reurn; 
} 
```
另一个线程A会调用LibAddTask方法，不断添加任务:
Another thread A will call the LibAddTask method to continuously add tasks:
```c
void func()
{
  while(1)
  {
     LibAddTask(task); 
  }
}
```

我遇到的情况是，假如我的一些后处理函数还在工作，那么A线程似乎就会阻塞.
I've had a situation where the A thread seems to block if some of my post-processing functions are still working.

**Comment by wqking** [comment]
How do you dispatch or process the event queue, such as call `eventQueue.process`?

**Comment by hctym1995** [comment]
> How do you dispatch or process the event queue, such as call `eventQueue.process`?

yes

**Comment by hctym1995** [comment]
```c++
LibAddTask(void *task)  
{ 
  eventqueue.enqueue(tasktype, task, mytype);  
  eventqueue.process();
  reurn; 
} 
```

**Comment by wqking** [comment]
`eventqueue.process();` should be called in the "background" thread.
So,
Thread A, call `LibAddTask`.
Other thread (such as the background thread), call `eventqueue.process();` .

`eventqueue.process();`  will block your current thread, so don't call it in `LibAddTask`.

I think I should make the document more clear.

**Comment by hctym1995** [comment]
Can I understand it like this:
I should create a thread B in my dynamic library,Thread B keeps process(), like this：
```c++
void LibProcess()
{
  while(1)
  {
    eventqueue.process();
  }
}

std::thread thd1(LibProcess);
thd1.join();
```

**Comment by wqking** [comment]
Yes. And the listeners are called from the thread in which `process` is called.

**Comment by hctym1995** [comment]
Understood, thank you very much for your prompt reply
If there is a chance, I will write my usage record into a wiki, I hope it can help others
