### ISSUE TITLE
Is there some problem with the insertListener function?

### ISSUE THREAD

**Issue by zhllxt** [wqking/eventpp#44]
`Handle insertListener(const Event & event, const Callback & callback, const Handle & before)`

if the "event" type is not equal to the "before" object's event type,  seems to cause problems ?

**Comment by wqking** [comment]
What problem?

**Comment by wqking** [comment]
I added function `ownsHandle` to check if the handle belongs the CallbackList or EventDispatcher.  
You should call `ownsHandle` before `insertListener` if you are not sure if `before` belongs to the dispatcher.
`insertListener` doesn't verify the handle for performance reason.

So your sample code will look like,

```c++
if(dispatcher.ownsHandle(5, listener)) {
    dispatcher.insertListener(5, []()
    {
        std::cout << "Got event 5." << std::endl;
    }, listener);
}
```

**Comment by zhllxt** [comment]
Thanks, Nice work.
