### ISSUE TITLE
no type named 'Mutex' in 'eventpp::MultipleThreading'

### ISSUE THREAD

**Issue by ToTheEnd7788** [wqking/eventpp#46]

**Comment by ToTheEnd7788** [comment]
```
#include <iostream>
#include <eventdispatcher.h>

using namespace eventpp;

int main() {
    eventpp::EventDispatcher<int, void()> dispatcher;

    return 0;
}
```


In template: no type named 'Mutex' in 'eventpp::MultipleThreading' error occurred here in instantiation of template class 'eventpp::internal_::CallbackListBase<void (), eventpp::DefaultPolicies>' requested here in instantiation of template class 'eventpp::CallbackList<void ()>' requested here in instantiation of template class 'eventpp::internal_::EventDispatcherBase<int, void (), eventpp::DefaultPolicies, void>' requested here in instantiation of template class 'eventpp::EventDispatcher<int, void ()>' requested here

**Comment by wqking** [comment]
What compiler do you use? I can't reproduce this error in both MSVC and GCC.
