### ISSUE TITLE
语法问题

### ISSUE THREAD

**Issue by bizehao** [wqking/eventpp#5]
大佬 研究你的代码 但是在

template<typename T>
            struct HasTypeCallback {
                template<typename C>
                static std::true_type test(typename C::Callback*);

                template<typename C>
                static std::false_type test(...);

                enum {
                    value = !!decltype(test<T>(0))()
                };
            };
块看不懂了  尤其是  value = !!decltype(test<T>(0))()  真的很迷

**Comment by bizehao** [comment]
研究了半天  算是看明白了  真的佩服这种想发  堪称黑魔法

**Comment by wqking** [comment]
哈哈，两个叹号是把值转成布尔的常用放法。至于decltype后面那堆括号，那是用来做SFINAE的，没办法，只能那么迷。
如果再有问题最好用英文，这样别人也能看看。

**Comment by bizehao** [comment]
好的  看了你的代码  我觉得我没学过 c++
