### ISSUE TITLE
maybe a typo in argumentadapter.md document

### ISSUE THREAD

**Issue by asmwarrior** [wqking/eventpp#50]
> each event type has its own event class, such as a mouseDown event has MouseDown event class.

I think the word should be:

> each event type has its own event class, such as a mouseDown event type has MouseDown event class.

Am I correct? 

Thanks.

**Comment by wqking** [comment]
Thanks, I fixed it and rephrased the sentence. The old one is difficult to understand.
It's not a typo. In the document, the word `event` may refer to the event type, though sometimes it may look ambiguous.

**Comment by asmwarrior** [comment]
OK, I think this typo is fixed now, so I will close this issue. Thanks.
