### ISSUE TITLE
Clang compile error

### ISSUE THREAD

**Issue by SplitGemini** [wqking/eventpp#52]
As below:
eventpp/include/eventpp/eventqueue.h:85:15: error: dependent using declaration resolved to type without 'typename'
[build]         using super::Handle;
[build]               ^
eventpp/include/eventpp/eventqueue.h:86:15: error: dependent using declaration resolved to type without 'typename'
[build]         using super::Callback;
[build]                      ^

clang version 6.0.0

**Comment by wqking** [comment]
Which code do you use? Seems your code is quite different with [the master](https://github.com/wqking/eventpp/blob/15d78b7bd2700ff13b596069a9e2a09ee14ad7f0/include/eventpp/eventqueue.h#L85).

**Comment by SplitGemini** [comment]
Oh, I use 0.1.1 and it seems that 0.1.2 doesn't have this problem. Sorry, my bad.
