### ISSUE TITLE
[Question] Are event cbs, after a dispatch, processed async or sync?

### ISSUE THREAD

**Issue by rolandjitsu** [wqking/eventpp#53]
I went through [eventdispatcher.h](https://github.com/wqking/eventpp/blob/master/include/eventpp/eventdispatcher.h) and I was trying to figure out if the event dispatching runs the cbs in a different thread, but it doesn't look like that.

Am I correct to assume that cbs are invoked on the main thread and are blocking? E.g, a cb, if it blocks, may prevent the event from being propagated to all the listeners?

**Comment by wqking** [comment]
You need EventQueue for asynchronous event. EventDispatcher can only do synchronous event.

**Comment by rolandjitsu** [comment]
> You need EventQueue for asynchronous event. EventDispatcher can only do synchronous event.

Ok. Thanks for clarifying that.
