### ISSUE TITLE
Thread safety ?

### ISSUE THREAD

**Issue by Thalhammer** [wqking/eventpp#55]
Hi, I stumbled across this library while researching for my own signal/slots implementation.
Unless I missread something the callbacklist class is supposed to support concurrent removal and iteration both from multiple threads and recursively (i.e. the callback removes itself). I might be wrong, but I don't think the current implementation actually does.

The issue I see is actually (kinda) documented in [doFreeNode](https://github.com/wqking/eventpp/blob/63497c60ef16bb3842812f75b97c6a48778affa1/include/eventpp/callbacklist.h#L382), where it says: 
```
// don't modify node->previous or node->next
// because node may be still used in a loop.
```
right after modifying the previous/next value of the node before/after the removed one. So while keeping the values in the removed node works in practice I am fairly sure this is a data race if another node is removed concurrently. Consider the following flow of events:
```
Thread A starts iterating the list
Thread A starts reading nodeX->next and gets interupted after getting part of nodeX->next
Thread B removes the node after nodeX (which in turn updates nodeX->next)
Thread A is resumed and continues reading the rest of nodeX->next which now contains different data.
```
The result is that ThreadA now has a invalid pointer that might or might not lead to a crash. The root of the problem is that assigning/reading a shared_ptr is neither atomic nor threadsafe ([thats why the free standing overloads of `std::atomic_load` for shared_ptr exist](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic)).

Please correct me if I am missing something, but I don't think the algorithm in the current form is actually thread safe (even if it might not manifest in practice).

**Comment by wqking** [comment]
Hello, `doFreeNode` is called by `remove` which is protected by `mutex`. Reading next happens in `forEach`, which is protected by `mutex` too. So I don't think there is data race problem.  
In brief, all reading (next/previous), assigning, and modifying, are protected by 'mutex'.

**Comment by Thalhammer** [comment]
Oh right, didn't see the mutex in forEach. Nvm then.
