### ISSUE TITLE
Confusion about the parameters of the `eventpp::EventQueue.enqueue`

### ISSUE THREAD

**Issue by Chaojimengnan** [wqking/eventpp#56]
In the following code:

https://github.com/wqking/eventpp/blob/63497c60ef16bb3842812f75b97c6a48778affa1/include/eventpp/eventqueue.h#L174-L189

Where 

```cpp
auto enqueue(T && first, A ...args)
```

Why does `A...` not add universal references, likes `A&&...`.

In my tests, there is extra move and destruct overhead (local variables) if the universal reference is not added. Is there any particular reason for this?

**Comment by wqking** [comment]
Thanks for spotting that out, good job.
I've fixed it by adding the universal reference. I think missing the && is for historical reason. The type `args` was not template parameter and it didn't make sense to make it universal reference, after I changed it to template parameter, seems I forgot to add the &&.
