### ISSUE TITLE
Dispatcher模板类型限定，如何适配任意的事件

### ISSUE THREAD

**Issue by jowu598** [wqking/eventpp#59]
看了下参考例子，有点不太理解，
```
eventpp::EventDispatcher<int, void ()> dispatcher;
```
就限定死了回调参数类型，那如果回调参数类型是int (int), 是不是还得声明
eventpp::EventDispatcher<int, int(int)> dispatcher;

**Comment by wqking** [comment]
回调函数参数类型不一定要跟事件声明完全一样，只要回调函数能按C++语法被调用就行。比如，
`eventpp::EventDispatcher<int, void (int)> dispatcher;`
那么 `int(int)`, `void (char)`，都可以用作回调。
但是，你那个例子，回调函数无法被调用，所以不能做回调函数。
