### ISSUE TITLE
Issues with Clang (-Wextra)

### ISSUE THREAD

**Issue by IsmayilMirzali** [wqking/eventpp#6]
The project I'm working on currently uses flags -Wall -Wextra -Werror -Wpedantic for compiling. I get unused parameters errors like so:
`/home/lemagicien/Development/winter/pawlib/pawlib-source/../../libdeps/libs/include/eventpp/eventpolicies.h:95:43: error:   
      unused parameter 'order' [-Werror,-Wunused-parameter]
                void store(T desired, std::memory_order order = std::memory_order_seq_cst) noexcept
                                                        ^
`

`/home/lemagicien/Development/winter/pawlib/pawlib-source/../../libdeps/libs/include/eventpp/eventpolicies.h:125:43: error:   
      unused parameter 'lock' [-Werror,-Wunused-parameter]
                void wait(std::unique_lock<std::mutex>& lock, Predicate pred)`

Are these intentional or an issue with eventpp? Compiling with Clang 7.0

**Comment by wqking** [comment]
It's not intentional nor any serious issue.
The error should be a warning but your -Werror turns it to an error.
I've made a fix at commit 311fb876ddef3ab252911e73a39efdaea8b06c26.
But I only tested with GCC, not Clang, and GCC can't reproduce the warning, so I'm not sure if all warnings are fixed. If not, just comment and give the warnings information.

**Comment by IsmayilMirzali** [comment]
> It's not intentional nor any serious issue.
> The error should be a warning but your -Werror turns it to an error.
> I've made a fix at commit [311fb87](https://github.com/wqking/eventpp/commit/311fb876ddef3ab252911e73a39efdaea8b06c26).
> But I only tested with GCC, not Clang, and GCC can't reproduce the warning, so I'm not sure if all warnings are fixed. If not, just comment and give the warnings information.

Made the changes and now it produced one error: (there could be more, it failed pretty early on)

`In file included from /home/lemagicien/Development/winter/pawlib/pawlib-source/../../libdeps/libs/include/eventpp/eventpolicies.h:17:
/home/lemagicien/Development/winter/pawlib/pawlib-source/../../libdeps/libs/include/eventpp/internal/typeutil_i.h:62:29: error: 
      unused parameter 'index' [-Werror,-Wunused-parameter]
        static auto find(const int index, C && c, Args && ...args)
                                   ^
1 error generated.`

**Comment by CodeMouse92** [comment]
@IsmayilMirzali You could edit our `CMakeLists.txt` file to temporarily drop `-Werror`, and then you'll get all the warnings at once, instead of one at a time.

**Comment by wqking** [comment]
@IsmayilMirzali , please follow @CodeMouse92 's suggestion, remove -Werror temporarily, then report all warnings.

**Comment by IsmayilMirzali** [comment]
@wqking It compiles just fine without -Werror. 

```
warning: 
      unused parameter 'index' [-Wunused-parameter]
        static auto find(const int index, C && c, Args && ...args)
```

It's the same warning repeated 12 times. Same file, same line. (typeutil_i.h:62:29)
Thanks for the help, for the time being, I'll stick to not using -Werror.

**Comment by CodeMouse92** [comment]
@IsmayilMirzali `-Werror` does have to be turned back on as soon as possible; we cannot commit code that has warnings (company standard), but once there are no warnings, it will compile fine with `-Werror`.

**Comment by wqking** [comment]
Fixed. Let me if there are any more warnings.

**Comment by IsmayilMirzali** [comment]
@wqking Thank you.
