### ISSUE TITLE
Heter Dispatchers - why aren't they default?

### ISSUE THREAD

**Issue by KyrietS** [wqking/eventpp#60]
Hi, firstly let me say that I really like your project 🫠!

I was looking for some event-dispatcher library for C++ and I found this. What I needed though was to be able to subscribe for *different* types of events and also dispatch *different* types of events. Your primary API provides only one event type per dispatcher. Of course I can use polymorphism and do the casting in every lambda I pass to the dispatcher but that's a little bit too much work for me 😅

So I was wondering... what was stopping you from making this library... well... more generic?
I made a short code sample that showcases the core functionality of your library but written in a more generic way:

```cpp
#include <iostream>
#include <functional>
#include <list>
#include <typeindex>
#include <map>

struct Dispatcher
{
    using Listeners = std::list<std::function<void(const void*)>>;
    std::map<std::type_index, Listeners> listenersByType;

    template<typename T>
    void appendListener(const std::function<void(const T&)>& listener)
    {
        listenersByType[std::type_index(typeid(T))].push_back([listener](const auto& msg) {
            const T* concreteMessage = static_cast<const T*>(msg);
            listener(*concreteMessage);
        });
    }

    template<typename T>
    void dispatch(const T& msg)
    {
        const auto& listeners = listenersByType.find(std::type_index(typeid(T)));
        if (listeners != listenersByType.end()) {
            for (auto &listener: listeners->second) {
                listener(&msg);
            }
        }
    }
};
```

And here is the usage:

```cpp
struct Message {};

struct MousePressedMsg
{
    int x, y;
};

struct Chicken {};

int main() {

    Dispatcher dispatcher;
    dispatcher.appendListener<MousePressedMsg>([](const auto& msg) {
        std::cout << "Mouse pressed: (" << msg.x << ", " << msg.y << ")" << std::endl;
    });

    dispatcher.appendListener<Message>([](const auto& msg) {
        std::cout << "Some message" << std::endl;
    });

    dispatcher.dispatch(Message{}); // prints "Some message"
    dispatcher.dispatch(MousePressedMsg{10, 20}); // prints "Mouse pressed: (10, 20)"
    dispatcher.dispatch(Chicken{}); // no listener for this type, but no problem

    return 0;
}
```

And as you can see, I don't need any strange EventPolicies. EventType is just a C++ type. It is a compile-time unique identifier. What's the benefit of having a long enum-list with event types separately?

Also, I can add listener for literally every type and dispatch every type of message.

You said yourself that you are a *big fan of observer pattern*. And as an author of this library you definitely have much greater knowledge than me in this matter. I am creating this issue to ask a simple, and maybe stupid question (sorry 😟): why isn't your library more generic, like in the example that I provided? Are there some limitations that I have not yet reached in my solution?

**Comment by wqking** [comment]
Hello,

If I remember correctly, there are other event libraries use your generic approach.  

The generic approach is only usable in synchronized EventDispatcher, it can't be used in asynchronous EventQueue. Most applications will use asynchronous event queue, such as Windows system, GUI applications, games, all of them relies on event loop. EventQueue provides such event loop. This is the best reason I don't use the generic approach in eventpp.  

Also, not every event needs a unique C++ type. For example, in a GUI application, it's common that there are events for key up, and key down, but they may share an event type such as KeyEvent.  

My first decision when making eventpp was NOT to use the generic approach. That approach may have more disadvantages I didn't list above.  

Fortunately, eventpp is so flexible that you can simulate the generic approach almost perfectly, below is the sample code. The only disadvantage is that you need free functions instead of member functions in EventDispatcher, of course you can inherit from EventDispatcher and put the functions in it.  

```c++
#include "eventpp/eventdispatcher.h"

#include <typeinfo>
#include <typeindex>
#include <iostream>

// The `const void *` is for using data structures that don't have the same base class.
// The user code is not aware of any pointers.
using MyEventDispatcher = eventpp::EventDispatcher<std::type_index, void (const void *)>;

template <typename T, typename Listener>
void genericAppend(MyEventDispatcher & dispatcher, Listener && listener)
{
    dispatcher.appendListener(std::type_index(typeid(T)), [listener](const void * e) {
        listener(*static_cast<const T *>(e));
    });
}

template <typename T>
void genericDispatch(MyEventDispatcher & dispatcher, const T & e)
{
    dispatcher.directDispatch(std::type_index(typeid(T)), &e);
}

struct KeyEvent { int key; };
struct MessageEvent { std::string message; };

void doTest()
{
    MyEventDispatcher dispatcher;
    genericAppend<KeyEvent>(dispatcher, [](const KeyEvent & e) {
        std::cout << "Generic key event, key is " << e.key << std::endl;
    });
    genericAppend<MessageEvent>(dispatcher, [](const MessageEvent & e) {
        std::cout << "Generic message event, message is " << e.message << std::endl;
    });
    genericDispatch(dispatcher, KeyEvent{ 38 });
    genericDispatch(dispatcher, MessageEvent{ "Hello eventpp" });
}
```

**Comment by KyrietS** [comment]
> The generic approach is only usable in synchronized EventDispatcher, it can't be used in asynchronous EventQueue. 

If I add one additional std::list and these two methods:
```cpp
    std::list<std::function<void()>> queuedDispatches;

    template<typename T>
    void queue(const T& msg)
    {
        queuedDispatches.push_back([this, msg]() {
            dispatch(msg);
        });
    }

    void process()
    {
        for (auto& queuedDispatch : queuedDispatches)
        {
            queuedDispatch();
        }
        queuedDispatches.clear();
    }
```
Then I can do asynchronous dispatching:

```cpp
    dispatcher.queue(Message()); // queues "Abstract message"
    dispatcher.queue(MousePressedMsg{ 10, 20 }); // queues "Mouse pressed: (10, 20)"
    dispatcher.queue(Chicken{});

    std::cout << "Before process" << std::endl;
    dispatcher.process(); // prints "Abstract message" and "Mouse pressed: (10, 20)"
    std::cout << "After process" << std::endl;
```

So I still don't understand what is not possible according to asynchronous dispatching. Maybe some corner cases with removing listeners on the fly 🤔?

> it's common that there are events for key up, and key down, but they may share an event type such as KeyEvent.

If they share the same event type, but they have different payloads, then you would still need two classes for these 2 event payloads (or they are as primitive as `int`, then okay 😄). So the advantage that we have here with eventpp is that you can listen for all `KeyEvent`s at once no matter what payloads of these events are 😋 (it's still possible with my example after some small modifications. Using inheritance you can have a listener for `KeyEvent` that will be called for every subclass of this type, e.g. `struct KeyDown : KeyEvent {}`)

But you definitely have a point here:
> Also it's not rare that many events don't need any data, defining a class for such event is overkill.

My solution requires a separate type for every event (such class can be defined in one line, but you're still right 😄)

And thank you for the example of making the same with eventpp. It looks almost identical and it's easier than I thought.

**Comment by wqking** [comment]
In your approach, it's difficult to support multiple arguments in listener. What to do if the first argument is `int`, and the second is `T`?  
eventpp is a general library, it needs to support all possible use cases, and as you can see, it doesn't enforce any limitations.  
Also, if the default in eventpp is the generic approach, then you can't simulate the enumerator identifier solution. As you already swa, it's easy to simulate your generic approach in eventpp.

**Comment by KyrietS** [comment]
Okay, I got it. Thank you for the explanation! 😀

**Comment by wqking** [comment]
Just an update, now we can implement the feature you requested almost perfectly, please check [the document](https://github.com/wqking/eventpp/blob/master/doc/tip_use_type_as_id.md)
