### ISSUE TITLE
如何实现不定参数调用？

### ISSUE THREAD

**Issue by dearbird** [wqking/eventpp#62]
eventpp如何能实现不定参数的回调
类似伪代码

Listen(1, [](int a, const std::string& b){...});
Listen(2, [](int a, int b){...});

Invoke(1, 3, "abc");
Invoke(2, 3, 4);

**Comment by dearbird** [comment]
使用 std:tuple 保存参数，然后unpck 调用，这样可以让函数原型一致
但是遇到新问题：  
Listent 时的参数类型是  std::tuple<int&>
Invoke 时的参数类型是 std::tuple<int> 不一致，cast 异常

**Comment by wqking** [comment]
eventpp 不支持不同参数的调用，而且你这种不是通常的事件派发。
eventpp 里有[异构的事件派发](https://github.com/wqking/eventpp/blob/master/doc/heterogeneous.md)，但那只是实验性质，而且以后也不一定会继续维护。
