### ISSUE TITLE
New version release (vcpkg)

### ISSUE THREAD

**Issue by vebjornjr** [wqking/eventpp#64]
Hi!

Any plans for a new release soon? It seems like there has been significant development (fixes etc) since version 0.1.2 (June 2022).

We manage our dependencies via vcpkg so cloning the master branch is not a preferred alternative.

Thank you!

**Comment by wqking** [comment]
Hi, it's fine to make a release. I will do it.

**Comment by wqking** [comment]
I've created a new version 0.1.3 release and submitted to vcpkg. Just wait for it to be approved by vcpkg.

**Comment by wqking** [comment]
Done
