### ISSUE TITLE
Function in CallbackList for removing all callbacks

### ISSUE THREAD

**Issue by vebjornjr** [wqking/eventpp#65]
Hey!

Thank you for this library.

I have a suggestion for a small improvement. In my use case it is quite common to want to remove all callbacks from the CallbackList. I know this can be acheived with the `forEach` function, but since I see this as a common and simple operation I think it makes sense to provide it as a simple function.

**Comment by wqking** [comment]
Hi, what's the use case to remove all callbacks from a CallbackList? You may simply assign an empty CallbackList to the existing one to "clear" it, isn't it enough?
Note if we add such "clear" function in CallbackList, we also need to add similar functions to EventDispatcher and EventQueue, to keep the API consistent.

**Comment by vebjornjr** [comment]
The use-case is when a ComponentA har registered several callbacks with a ComponentB (which uses CallbackList internally). Often we want to unsubscribe (remove) the callbacks as the first step in the destructor of ComponentA so that it no longes receives callbacks. ScopedRemover will not work (as I see it) since we want to remove the callbacks before doing other clean-up in the destructor.

I will take a look at assigning an empty CallbackList.

**Comment by wqking** [comment]
After careful consideration, I think it's not necessary to add such function.
There are several alternatives to achieve this,
1, Assign the existing CallbackList with an empty CallbackList.
2, Or use the `reset` function in `ScopedRemover`.
