### ISSUE TITLE
Break on receiving false from callback/event dispatch?

### ISSUE THREAD

**Issue by ga2k** [wqking/eventpp#69]
It seems the callback mechanism doesn't use return codes. I have some callbacks in my self-written and probably buggy dispatcher code that has the format of

Highest Priority callback target
High Priority callback target
Normal Priority callback target
Low priority callback target.

In my code, the callback target with the priority "Highest" may, when called, look around and see things aren't ready yet, and so returns false. The dispatcher sees the false return and aborts.

This arrangement supposes a priority system can be implemented, and that callback functions return a value true (continue) or false (abort)

Is this something you have considered?

I guess failing this, I could write a handler that functions as priority level, and all, say, Highest priority callbacks subscribe to. Then if the event should propagate, it calls the next lower priority level, and so on through the whole hierarchy.

**Comment by wqking** [comment]
Fortunately, all you needs are covered by `eventpp`.  
For returning `false` to break the dispatch, see [the canContinueInvoking policy](https://github.com/wqking/eventpp/blob/master/doc/policies.md).  
For priority dispatching, see [OrderedQueueList](https://github.com/wqking/eventpp/blob/master/doc/orderedqueuelist.md). Warning, its performance is not optimized, you are welcome to contribute better implementation.

**Comment by ga2k** [comment]
Seems there is plenty already available to achieve what I want. I'm closing this.
