### ISSUE TITLE
Conan instructions

### ISSUE THREAD

**Issue by RazielXYZ** [wqking/eventpp#70]
Now that eventpp is on conancenter you can add instructions on how to use it from there
I don't know if going over the full conan setup for a project is required/in-scope for the eventpp docs but the basics would be:

1. Have python and conan installed (of course)
2. In your project, assuming CMake, add a conanlist.txt file that should contain 
```
[requires]
eventpp/0.1.3

[generators]
CMakeDeps
CMakeToolchain
```
3. In your CMakeLists, add
```
find_package(eventpp CONFIG REQUIRED)
target_link_libraries(${TARGET} PRIVATE eventpp::eventpp)
```
4. Run `conan install . --output-folder=build --build=missing` in your project folder (assuming the default conan profile exists and is okay)
5. cd into build, run `cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -G "Whatever generator you want" -DCMAKE_BUILD_TYPE=Release`; alternatively it can also use cmake presets instead of passing the toolchain file on cmake >=3.23

And that's it. Some other notes for conan usage:

To handle different configs (release/debug, x86/x64), the best way is with conan profiles and passing them in with -pr to conan install. When used with cmake, use different --output-folders for each config even with multi-config generators since I think conan can't generate multi-config toolchain files for cmake. However considering eventpp is header-only this would only pertain to the project that uses conan and not so much to eventpp.

Conan can handle multiple versions of a dependency and does expect you to specify what version you want. Right now only 0.1.3 is on conancenter. If one just wants to always get latest, you could use eventpp/[>=0.1.3] under requires and add --update to the conan install command to make sure it checks if there's any revisions or new versions.

Feel free to ask if there's any other questions!

**Comment by wqking** [comment]
Thank you so much for adding eventpp to Conan. I've [add the Conan usage here](https://github.com/wqking/eventpp/blob/master/doc/install.md). Please let me know if any thing in the document need to improve.

**Comment by RazielXYZ** [comment]
That seems good to me! I don't think going into more conan-specific details would really be suitable for the docs here. Conan has good tutorials and documentation on their website too.

**Comment by RazielXYZ** [comment]
If you want, you could add shields to the top of the main readme for people to quickly see that the library is available on vcpkg and conan
[![Vcpkg port](https://img.shields.io/vcpkg/v/eventpp)](https://vcpkg.link/ports/eventpp)
[![Conan Center](https://img.shields.io/conan/v/eventpp)](https://conan.io/center/recipes/eventpp)
```
[![Vcpkg port](https://img.shields.io/vcpkg/v/eventpp)](https://vcpkg.link/ports/eventpp)
[![Conan Center](https://img.shields.io/conan/v/eventpp)](https://conan.io/center/recipes/eventpp)
```

**Comment by wqking** [comment]
The shields are nice, I will add them. Clicking the conan shield causes 500 internal error on Conan website, and I can't find eventpp recipe on Conan. Maybe it needs time to update, I will commit the shields after it's available on Conan.

**Comment by RazielXYZ** [comment]
Yes, it needs time to update, but it is actually available on the server already, it's just the website that lags behind. If you do `conan search eventpp*` it will already show up, and projects can already use it as a requirement. No issues with waiting a bit until the website updates too though!
