### ISSUE TITLE
Remove Listener Example

### ISSUE THREAD

**Issue by DarkTyger** [wqking/eventpp#72]
Re: https://github.com/wqking/eventpp?tab=readme-ov-file#using-eventqueue

Please include a working example showing how to delete event listeners from the queue.

``` c
#include "eventpp/eventqueue.h"
#include "eventpp/utilities/eventutil.h"
eventpp::EventQueue<int, void (const std::string &, const bool)> queue;

queue.appendListener(3, [](const std::string s, bool b) {
    std::cout << std::boolalpha << "Got event 3, s is " << s << " b is " << b << std::endl;
});
queue.appendListener(5, [](const std::string s, bool b) {
    std::cout << std::boolalpha << "Got event 5, s is " << s << " b is " << b << std::endl;
});

// The listeners are not triggered during enqueue.
queue.enqueue(3, "Hello", true);
queue.enqueue(5, "World", false);

// Process the event queue, dispatch all queued events.
queue.process();

// Remove the listener when no more processing is needed.
removeListener( queue, ..., ... );
```

**Comment by wqking** [comment]
The example code doesn't need to include every functions. You may refer to [the document](https://github.com/wqking/eventpp/blob/master/doc/eventdispatcher.md) for how to remove listeners.  
And you may like the utility class [ScopedRemover](https://github.com/wqking/eventpp/blob/master/doc/scopedremover.md).

**Comment by DarkTyger** [comment]
> The example code doesn't need to include every functions.

It took me _hours_ to figure out the syntax for how to remove listeners, mostly because it wasn't clear to me that we needed to capture the subscription token from `appendListener`. Having a working example for calling `queue.removeListener` would have saved me a lot of time. The solution I came up with is O(n), though.

Certainly, not every function needs to have an example. An example for removing listeners would likely save others a fair amount of time. Especially if an O(1) solution for removing listeners is possible.

FWIW, I've read the documentation and it didn't help me. There are many technical details missing. That's why an example is useful.

**Comment by wqking** [comment]
I've improved the EventQueue document, added a link to EventDispatcher for how to add/remove listeners.  
You never need eventpp::internal_, seeing you are using CallbackListBase instead of CallbackList, and implement your own EventBus instead of using EventQueue or EventDispatcher, apparently you didn't read any eventpp document. Please read the document, you can't get all knowledge from sample code.

**Comment by DarkTyger** [comment]
>  apparently you didn't read any eventpp document

That's an accusatory statement, which is neither necessary nor correct. We read the documentation, especially the helpful eventqueue.md page. We implemented an EventBus, which is a thin wrapper around an EventQueue, to avoid coupling the rest of the system to eventpp, in the case we need to switch out for a different message dispatch system.

**Comment by wqking** [comment]
The documents cover all information you need. The example code won't be changed.
