### ISSUE TITLE
Correct checking whether queue is empty

### ISSUE THREAD

**Issue by UnrealDoggie** [wqking/eventpp#75]
Hi,

My use case is having a thread do reading data entry from a file & enqueue to eventQueue.
After reaching end of file, the file rewinds to replay.
The main thread (opengl rendering) is the one calling  eventQueue.process()

//Reading Thread
// In rewind function, wait for all events to be processed in the main thread!
while (eventQueue.waitFor(std::chrono::nanoseconds(0))) // Copied from test cases
{
std::cerr << "Waiting for Queue To be Empty!....." << "\n";
}
// Once queue is empty,  start reading data entries again

//Main Thread - OpenGL
while (window.notclose)
{
     eventQueue.wait();
     eventQueue.process();
}

My issue is that after several loops(more than 5 mins), rendering seems to slow down, so I would like to confirm if
I am using eventpp queue correctly before looking at other possible bugs.
Specifically, is my understanding correct to 
1) use waitFor in reading thread to allow all remaining events to be processed first before starting a playback from start again.
2) use wait() in main thread before processing.

Thanks in advance!

**Comment by wqking** [comment]
Your understanding is fine. You'd debug the slow issue.

**Comment by UnrealDoggie** [comment]
> Your understanding is fine. You'd debug the slow issue.

Thanks for confirmation!
