### ISSUE TITLE
If it is possible to control the order in which listeners are invoked?

### ISSUE THREAD

**Issue by RWBYBING** [wqking/eventpp#76]
In my understanding, in the eventQueue, when an event is being processed, all listeners will be invoked in the order of they were added. I'm not sure if I understand correctly, if my understanding is correct, I would like to ask if I can customize the order of listeners.

In my case, an event is listened by multiple modules, I cannot make sure the order of which those listeners were added. But I do need to let one module process it first. How can I deal with this situation?

**Comment by wqking** [comment]
>> when an event is being processed, all listeners will be invoked in the order of they were added

Yes, your understanding is correct. So you can control the order of adding listeners to make the invoking ordered.  
There is no other way to control the invoking order, and it will be added because it's anti-pattern.

**Comment by RWBYBING** [comment]
Get it. Thanks!
