### ISSUE TITLE
eventDispatcher could not register class member function?

### ISSUE THREAD

**Issue by micheal158235** [wqking/eventpp#8]
appendListener(const Event & event, const Callback & callback) in the class EventDispatcherBase, the "callback " could be Class Member Function? How to use?

**Comment by ludekvodicka** [comment]
boost::bind or std::bind ?

**Comment by wqking** [comment]
Like ludekvodicka said, use `std::bind`.  
Example, `std::bind(&YourClass::theFunction, pointerToYourClassObject)`, then use the bound object as the listener.
